define({
  root: ({
    _widgetLabel: "اندازه گیری",
    selectDrawMode: "انتخاب ابزار",
    clear: " حذف ",
    point: "نقطه",
    line: "خط",
    polyline: "خط",
    extent: "Envelope",
    polygon: "پلیگون",
    text: "متن",
    style: "قالب",
    alpha: "شفافیت",
    width: "پهنا",
    size: "اندازه",
    color: "رنگ",
    markerColor: "رنگ نشانگر",
    outlineColor: "رنگ حاشیه",
    lineColor: "رنگ خطوط",
    fillColor: "رنگ درون",
    showMeasurements: "نمایش اندازه ها",
    showTotals: "نمایش مجموع اندازه ها",
    areaUnits: "واحد مساحت",
    distanceUnits: "واحد فاصله",
    kilometers: " کیلومتر ",
    miles: "مایل",
    nauticalMiles: "Nautical Miles",
    meters: " متر ",
    feet: "فوت",
    yards: "یارد",
    squareKilometers: " کیلومتر مربع ",
    squareMiles: "مایل مربع",
    acres: "Acres",
    hectares: "هکتار",
    squareMeters: " متر مربع ",
    squareFeet: "فوت مربع",
    squareYards: "یارد مربع",
    undo: " قبلی ",
    redo: " بعدی ",
    results: "نتایج",
    points: "نقاط",
    lines: "خطوط",
    areas: "محدوده"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "vi": 0,
  "zh-cn": 0
});